### ISSUE TITLE
Exception has occured. File could not be loaded. (Note, Pandas needs to be 0.17.x or higher.)

### ISSUE THREAD

**Issue by xiaotinglei** [TiesdeKok/ipystata#12]
`import pandas as pd`
`import ipystata`

`%%stata -o df`
`sysuse auto, clear`

the above is right. when i use my stata data, ipystata is wrong.

`%%stata -o df`
`use E:/projects/project2/Data/CGSS2006.dta,clear`

Exception has occured. File could not be loaded. (Note, Pandas needs to be 0.17.x or higher.)

however, my pandas is above 0.17.x

how resolve this problem?

**Comment by TiesdeKok** [comment]
This error indicates that ipystata could not load the data back to Python. In many cases this is due to Stata saving to a file-format that older version of Pandas cannot load, hence the note in the error message. However, in your case this error is probably caused by something else. 

Could you try adding the `-os` argument so that the Stata window remains open? I suspect that Stata cannot save the file, if this is the case you should be able to see the error if you use `-os`.

**Comment by TiesdeKok** [comment]
# Closed because no response.
