### ISSUE TITLE
Multiple graphs per cell

### ISSUE THREAD

**Issue by bquistorff** [TiesdeKok/ipystata#25]
It would be great if it were possible to show multiple graphs per cell (like `ipython` [can](http://nbviewer.jupyter.org/gist/Tooblippe/6151560)). I believe this could be done by keeping track of the graph-data before and after a cell is run to see if any are new. Stata's `graph dir` lists the graph names. New graphs would be those that have new names or have been regenerated (the date and time can be checked with `graph describe <name>`). Graph exporting and display likely would be the same. This approach could be always done, removing the need to explicitly use `-gr`.

**Comment by TiesdeKok** [comment]
Great idea, you are right that my current approach is the limiting factor to supporting multiple graphs per cell. However, I was not aware of the `graph dir` and `graph describe` features. Once I find some time I will look into this further!

**Comment by kylebarron** [comment]
@TiesdeKok I hadn't seen this but this is actually exactly how I keep track of graphs: https://github.com/kylebarron/stata_kernel/blob/ef177e31d69fc33434176667e1c32b8d86850766/stata_kernel/kernel.py#L211-L228

Though currently my implementation necessitates each graph within the same block to have different names. I think that can be fixed by finding the commands in the block that create graphs and interspersing the code to export the image immediately after the command to create the graph.

**Comment by kylebarron** [comment]
I actually changed my method significantly in `stata-kernel`. We had some issues using `graph dir` and `graph describe`. Multiple graphs in the same cell that weren't explicitly given separate names would overwrite each other. And I wouldn't want to try to parse the user command to change the names of graphs.

Instead, we add a `graph export` command after every graph keyword that the user writes. In order to not overwrite other graphs, we have a global in memory named `stata_kernel_graph_counter`, which starts at 0 and increments by 1 each time a graph is exported. `stata_kernel` stays in sync with Stata just by reading the log and parsing the name of the file the graph was exported to.
