### ISSUE TITLE
Able to be used in Python shell?

### ISSUE THREAD

**Issue by kylebarron** [TiesdeKok/ipystata#31]
Is this able to be called directly from Python, instead of as a cell magic within IPython? For example, it would be really nice to be able to call a command like
```python
car_df = run_stata('sysuse auto', return_data = True)
```

Apparently, it's [possible to run built-in magics from python](https://stackoverflow.com/questions/10361206/how-to-run-an-ipython-magic-from-a-script-or-timing-a-python-script) with 
```python 
from IPython import get_ipython
ipython = get_ipython()
ipython.magic("timeit abs(-42)")
```
but `ipython.magic('stata di "this is stata"')` returns 
```
ERROR:root:Line magic function `%stata` not found (But cell magic `%%stata` exists, did you mean that instead?).
```

**Comment by TiesdeKok** [comment]
Hi @kylebarron, I looked into it and it turns out that `ipython` has the function `run_cell_magic` that you can use to call `ipystata` (`ipystata` only works as cell magic, not with line magic for which you would use `run_line_magic`). 

To illustrate: 

![image](https://user-images.githubusercontent.com/13317782/34148664-846ed1de-e4a2-11e7-978a-ba4c57dcc149.png)

Thanks for hinting me to the `ipython.magic()` command, I was not aware that you could do this with `ipython` but I certainly have some use cases of my own for this!

Feel free to close this issue if this answers your question.

Ps. as an aside, it would be interesting to evaluate whether it would be possible to port some of your https://github.com/kylebarron/language-stata code to work with the `CodeMirror` editor that Jupyter uses for syntax highlighting. My currently solution is very bare bones and is not working with more recent version of Jupyter so I am looking to update and fix this functionality when I find some time.

**Comment by kylebarron** [comment]
This still doesn't work outside the IPython kernel, though. Is it possible to get the `get_ipython()` call from the package to see the `get_ipython()` function in the current namespace?
```
> python3                     
Python 3.6.1 (default, Jun 28 2017, 17:51:18) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> from IPython import get_ipython
>>> ipython = get_ipython()
>>> import ipystata
IPyStata is loaded in batch mode.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/nber/barronk/.local/lib/python3.6/site-packages/ipystata/__init__.py", line 10, in <module>
    from . import ipystata_magic_batch
  File "/homes/nber/barronk/.local/lib/python3.6/site-packages/ipystata/ipystata_magic_batch.py", line 250, in <module>
    ip = get_ipython()
NameError: name 'get_ipython' is not defined
>>> 
```

**Comment by TiesdeKok** [comment]
I am afraid that this approach will only work within the IPython kernel (when I put everything in a .py file and run it with ipython file.py it works without a problem). 

Obviously my code to interact with Stata is perfectly suitable to run using a regular Python function instead of a ipython magic function. However, this would require some rewriting to convert the magic functions to regular functions. I don't expect this to be too difficult, but as with anything it would take some effort.

**Comment by kylebarron** [comment]
> Ps. as an aside, it would be interesting to evaluate whether it would be possible to port some of your kylebarron/language-stata code to work with the CodeMirror editor that Jupyter uses for syntax highlighting. My currently solution is very bare bones and is not working with more recent version of Jupyter so I am looking to update and fix this functionality when I find some time.

Sorry I don't think I saw this the first time. The syntax highlighting that Codemirror uses is non standard and you can't really adapt language-stata to use it.

I was looking through this today because I'm considering making an actual Jupyter _kernel_ for Stata, which differs from your package, which is just a magic within the Python kernel to send commands to Stata. I think I've devised a basic pseudo Automation mode for Linux, which would allow for an actual kernel without ever having to move the data to Python, which is prohibitive when the data is large.

**Comment by TiesdeKok** [comment]
You should definitely consider making a standalone kernel, it is something that I would have already coded up myself if it wasn't for time constraints. Creating this should be straightforward (as no interoperability and data movements are required), it is "just" a kernel after all 😉. 

An unmaintained attempt at a Stata kernel can be found here: https://github.com/jrfiedler/stata-kernel/blob/master/stata_kernel/stata_kernel.py

I can help coding some parts of it if you want. Also, I'd be interested to hear about your "psuedo Automation mode for Linux", I am very curious what you came up with (as it might be worthwhile implementing into ipystata).

**Comment by kylebarron** [comment]
I'd been trying to think of a way to incorporate interprocess communication with stata for a while. It's quite a hack. Basically, I have a code folder, here `~/.config/stata-exec-inotify/`. I start from `0.do` and use [inotify-tools](https://github.com/rvoicilas/inotify-tools) to block Stata and wait for that file to be saved. Once it's saved, Stata runs that portion of code and waits for `1.do`. Ideally, the Python code that forms the Stata kernel will be able to keep track of which number Stata is expecting.

This might be too unstable. I'm worried that the timing between Python and stata will be off.

```stata
* Args with inotify path
global HOME : env HOME
local code_dir "$HOME/.config/stata-exec-inotify"
!mkdir -p "`code_dir'"
local counter = 0
local stop "False"
while ("`stop'" != "True") {
    !touch "`code_dir'/`counter'.do" && $HOME/local/bin/inotifywait -e close_write "`code_dir'/`counter'.do"
    * log start
    do `"`code_dir'/`counter'.do"'
    * log end
    local ++counter
}
```

**Comment by TiesdeKok** [comment]
Hmm, I see what you are doing. So that would work as follows:  

1. Python starts a Stata instance using the batch mode that runs a do file to start the above loop
2. Every time a cell is executed a new do file is created that is then picked up by the Stata loop 
3. A log file is created that is then picked up by Python to create the output in the notebook

Step 2 and 3 would repeat every time a new cell is executed. 

It is quite clever to have Stata wait like that. But if I understand it correctly it would require users to install `inotify-tools` for it to work right? 

--- 

Another approach might be to automate the interactive console mode of Stata, this would allow continuous interaction with Stata (instead of using the batch mode). I haven't tried this yet, but I am pretty sure that it should be possible to use the `subprocess` library to "interactively" interact with it. Another option might be to use the [`pexpect`](https://github.com/pexpect/pexpect) library, although I have never used it before.

**Comment by kylebarron** [comment]
Yes. Yes it would, but it's also quite possible that the Python install script could install inotify-tools. I would assume Linux users would be capable of doing that.

---

Wow pexpect is incredible. I had seen references to it but had never tested it out. It's by far the better option. I should be able to have a working prototype pretty quickly for Linux/mac using pexpect. But I'd still have to implement a hack for making graphs.
