### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by cschwem2er** [TiesdeKok/ipystata#4]
Hi, 

first of all thank you so much for creating ipystata! As an avid Python/Stata user I am very excited to see the development of this project.

Is there any chance to you will enable plots within the notebook?
After trying out

```
%%stata
hist mpg"
```

in your example notebook, the default parameters are printed 

```
(bin=8, start=12, width=3.625)
```

but not the actual plot.

**Comment by TiesdeKok** [comment]
Hello,

Thanks, it is rewarding to hear that people find it useful!

Coincidentally I realized yesterday that plot support would be a great addition. 

I am going to think of a way through which I can achieve that. It is a bit tricky because, even with Stata Automation, Stata does not allow me to directly pipeline the feedback of a command back into Python. I currently use the log file to temporarily save the output and then parse it to make it suitable for presentation in the notebook. 

Thank you for suggesting it, I will put it on the to-do list.

**Comment by cschwem2er** [comment]
Maybe it would be possible to use Statas graph export capability to temporarily store a graph in the working directory as an image, then loading this image into the notebook and deleting the image file again? This would be a very dirty approach but I imagine it is not too hard to implement.

**Comment by TiesdeKok** [comment]
I have added plot functionality using the `-gr` or `--graph` arguments. A %%stata cell with this argument will attempt to save and load + display a graph generated in that particular cell.

Let me know if you run into trouble using it!

**Comment by cschwem2er** [comment]
Thank you, it works perfectly! :) I just noticed a warning when importing ipytstan after updating to IPython 4.

```
C:\Anaconda3\lib\site-packages\IPython\utils\path.py:264: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module
  warn("get_ipython_cache_dir has moved to the IPython.paths module")
```

But this does not effect any funcionality as far as I can tell.

**Comment by TiesdeKok** [comment]
Great! It is on my to-do list to go through my code and make sure it is compatible with IPython 4, I guess it is a good sign that it appears to work with only a warning.
